# manifests/service-canary.yaml
apiVersion: v1
kind: Service
metadata:
  name: zero-downtime-app
  labels:
    app: zero-downtime-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8081
  selector:
    app: zero-downtime-app
