apiVersion: v1
kind: Service
metadata:
  name: zero-downtime-app-stable
  labels:
    app: zero-downtime-app
spec:
  ports:
    - port: 80
      targetPort: 8081  # make sure this is a different port than your main app
  selector:
    app: zero-downtime-app

