apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../manifests/service.yaml
  - ../../manifests/rollout.yaml
  - ../../manifests/hpa.yaml
  - ../../manifests/configmap.yaml
  - ../../manifests/secret.yaml

commonLabels:
  app.kubernetes.io/name: zero-downtime-app
  app.kubernetes.io/instance: zero-downtime-app
  app.kubernetes.io/version: v1.0.0